version: '3'
volumes:
  postgres_data:
    driver: local
services:

  db:
    image: postgres:10.5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    command: bash -c 'rm -f tmp/pids/server.pid & bin/webpack --watch --progress --color & bundle exec rails s -p 3000 -b "0.0.0.0"'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/client
      - ./client/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "3001:3001"
    depends_on:
      - api